// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoXuKQgRPL43uVwkv4U-oYoxNODQRJvM4',
    appId: '1:767386736203:web:4645e1612f3112ef5b5fce',
    messagingSenderId: '767386736203',
    projectId: 'mini-26d15',
    authDomain: 'mini-26d15.firebaseapp.com',
    storageBucket: 'mini-26d15.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxQJpp6PHA0lQ4zvnurrYlpChqgE7r6U',
    appId: '1:767386736203:android:ded28b42a86c82f25b5fce',
    messagingSenderId: '767386736203',
    projectId: 'mini-26d15',
    storageBucket: 'mini-26d15.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9J7To62Kic09l0Gz7npfHBiMjk70pp0A',
    appId: '1:767386736203:ios:948c0575507c49775b5fce',
    messagingSenderId: '767386736203',
    projectId: 'mini-26d15',
    storageBucket: 'mini-26d15.appspot.com',
    iosClientId:
        '767386736203-g9ua3f06ilbmkafka9unorbmn6roqehu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9J7To62Kic09l0Gz7npfHBiMjk70pp0A',
    appId: '1:767386736203:ios:948c0575507c49775b5fce',
    messagingSenderId: '767386736203',
    projectId: 'mini-26d15',
    storageBucket: 'mini-26d15.appspot.com',
    iosClientId:
        '767386736203-g9ua3f06ilbmkafka9unorbmn6roqehu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mini',
  );
}
